Repository openZH/covid_19, pull requests merged in 2020-04, with the labels that each got.

#366 Enhance BS data with two new columns
  fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_BS_total.csv
Labels: data update, enhancement

#356 Update COVID19_Fallzahlen_Kanton_TI_total.csv
  fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_TI_total.csv
Labels: data update

#355 Specify which columns cover residents of current canton only, …
  README.md
Labels: documentation

#421 Update COVID19_Fallzahlen_Kanton_NE_total.csv
  fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_NE_total.csv
Labels: data update

#528 Update COVID19_Fallzahlen_Kanton_JU_total.csv
  fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_JU_total.csv
Labels: data update
